language: go
go:
- 1.12.x
services:
- docker
env:
  global:
  - GO111MODULE=on
  - secure: Ro+5WUbz5URYG+fwsMODrdAClATnsUayDuU3IdDjS8PBY0GWYaYgUmHEODkOPPT+vehR1RA72MrhKBIUaZhyQjwlXEcUhpYlSkVH955EBfmycDqcWl0gDVfc5X1E7E1oCiu4UIZrwWlY6F4fNNVlNN3GfM+MVSozYO/HJES6eadp21khzEsOvCAuU/GwywfVa4r60VdbCekK3UgyVSfmZ2B0kk1B5uhkEl/Qsjf5z2s0GvTpPF4nR6W+BEGEXu22JvhW6hldLstEYSjSMnauN8heyFdl/6z8XRy8uZUSj9KN8u+kFi27RHayC3+7ywumywfdhNosYFRTbiPNzEzKwSn9HaCD8yJf62W1b8nMLaEKlzHGJVrOapqJ73ZQ8xZj1TeWOszf2uPT5zjhFEu10aUboZgfxQhVN9/XsIpZ3tlYEOCvoSCWJ1ZJQLvtozX2NEhIVLE1Rr7POLfmZgbgh8372tugJsNlSyRRR4ImpJCWtCW7ZEYSJVQQRtEtI1oZcRTMoEz0mtCxDyQdqIyY3+vZmE/9Rq41WHyUi/HCZ5PlEn2T308wnQDv9V76CLmgHDWBmshXf5nLuHrLOvvy4du6zNBVqsun9EX9t/zuPMu8uAUiPTH8LKx/LEsI9ShzFn8AbgDfVxr1Gm8VNDzh1MjvSZQdj3IfNh+3cMkNNeI=
  - secure: AtxHNfwcZ7j0TCDFbQWoGq4tAf1aryOppUGxPe2Y9oP3tcld0WL8FHSfyVzwi3QPKdnPTji8ycv9OjecWywLZOY1BFzxpndq2nEBGSKDFRM2I8dllaQVb/JDtcYepGaWX+zT5BzM6TkTHSASfNoI0TOfctZx5oGp8WQ9WGZLQKRz+lfSYlo4e3pj5AdCC/Al4jND2YQ7PI7z5wNB4VHjUd2LFNs8c1onZ8MenvbBv6/AGzt2yfRA63m7WQnONBvgaVI8gf6MUDWlzNIsJmEC2ccdCUl4LZS+kjlK5GOHafYIN0Q1wwLgI/GnWFbLJX4rHs5H22+VcioHzAi16ly//T7YfUJ2gv5j9iZUAvXB5/ffsK7+42sL5xCstvsMeRuqFQGpXdTqYRPabRDWm6ruaq2caShyj0Q2UuBpTK03+UdYHQmaX1l16s8SQ/RgN2X4WGTBTT9PH2yBbZHgiBoxT70fAPRNksO3baZ+zDoEikjVud/YwegV8R1MQjTy4xGmTUmP5zl1LZtSwomuaku/jjTlo13o88qF3CDcodI3uXZZvvW4HKJEcqsqQvMTBqKQKLAi2RnMAGDr7f2nlZKKDSr0HDfBJO8NU6HpMokk5jw3TALidC3ArvahGU6tRY9mzhOO4s6ODeK5kGsGJJXJ09ZpLWSq9bD6vagBh/+0NS0=
before_install:
- docker build -t altemista-billing .
# Is now a server, docker run does not return anymore
# requires further testing logic or auto-termination before reenabling the next line
# - docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY altemista-billing
script:
- go test ./...
