language: go
go:
- 1.12.x
services:
- docker
env:
  global:
  - GO111MODULE=on
  - secure: N1VJtcf1B6tgM5TZlZa7Ooh3AxhRjSAtEH3szmmE4vBwcRdsOvkM9tjkoCeV8E7Zm34dDRZOCQrFNQDHxLaiIAv5HeYUYPLdKFLrBOB//PUYokMdoswFjenvkSS+Bn/13hk5msexvbmil5KeGyhg20RoG0Y8yoLSrsGy5GDjyvxDr0kA0jlT1CavxtFenPYvRu0qEUpw2uRNW+fizM9HCGUC9FXJVZ4AJXCSXWnmow17D29WfDckfIIarERPb8kS3WlKRpLOe8+ygsaZhoLj+KDp7Ff9x2rtzWyE3J51F/DBYMvdo5IUuZpCWWeFvJWx4aFZtKjjTlKuUTxmM8Hq4+TBKcnb0BmXV+WXr64HMJuTYv+/scYI5RjTrFd6n3UawGs5ln13lX0342IkbsQ0v0o+O0tpeAzJQSEAlrcg5XdfUOrrJL9PQWtpgfVXtdAjFbLoJN/JCaHP4iSzhv44XBTsXISF6yyJ3rUwoZYrDLswGf55v7jHLSv4vOv16gSHcjQxUrPUe1xUFYs5r6n6DI8vuybT5KCHF1KsoghowPCmZtm2X8HYREVijPf2rlyRmB8izpRHrcdGoZ+R+fw+JgWLhpo4gZE+ZF+ZWghxSBi3aplJHExOM+4GEKfbrTD2ZrhoEMstUYiq+a7+iuyeIARMl8+f2tldy/oWFJSnJYU=
  - secure: UTvj21eouFYTAWYt+Z/jv32HNoYwwUZp6s5nzDfmtoTDzZgzpgGFaOOZwK/ZYMllhBZ/LiS8uV2wfGQcaeiao+E9paB+lj+CLDuvHa2PWTHI1p9FBZoVMX96SpvKlSHDwtfvdrmr9aeyUYUnnakZ7qqQLDBW84PkrwXHeonLpl8yCiT+RsZBcAZQqVGkAjGvXueV+tUdhW9AZW0H75g1qxDxp5sLrRrlhlq0hTVN71GSJmsBs88Mo+7YRet8z4wYAfs6K0m7MdZXTBqxRSI1RGE1Dk0ScNnFwUheVmlVwzdB2bP92JDGasH0tJeb6sjyW71CgurtrsPYfoRRQUa+cVEh10++fPOo2H4rSsgXY5GAudW3IzOWkRG7a3biTmQsMXA2hJNOGIO7cKSY8CUK+kJTbFS2KFeBTnUBXegqP71QbL1KntbYjGc8plTW34T9k8UjN0QzmXul12lyUr2IHSDHdA4MRoJCONGj1yaCcfxCJ97ErGfWfqD/DRFmU9/uxo/+TksS/kPLZhn63UJGBF9mAN//R9iptVp0/97TvvETB3USEFOaxN5cQ90RK6WqrRUjDayNVZuCbbxbIkyJmpYGYxw6t7jiWbRaW60g29KFtuBfV9Bo5oqPZhwB5yUFF4YFxUsaLc4cw7h/Uf7eZISNf35CxoYBWrLn8KVUbfc=
before_install:
- docker build -t altemista-billing .
- docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY altemista-billing
script:
- go test ./...
