apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: altemista-billing
spec:
  schedule: "0 4 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: altemista-billing-container
            image : altemista/altemista-billing
            args:
            - /app/billing
            - invoice 
            - --month last
            - --provider 
            - aws
            - --bucket
            - altemista-test
          restartPolicy: OnFailure
