apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: altemista-billing
spec:
  schedule: "0 4 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: altemista-billing-cron
            image : altemista/altemista-billing
            args:
            - /app/billing
          restartPolicy: OnFailure